#!/usr/bin/env bash
# Hello world Nginx

sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start
sudo sed -i "28i \\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
sudo sed -i "/server_name _;/ a\\\n\terror_page 404 \/custom_404.html;\n\tlocation = \/custom_404.html {\n\t\troot \/usr\/share\/nginx\/html;\n\t\tinternal;\n\t}"  /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html
sudo service nginx restart
