#!/usr/bin/env bash
# Bash script that install and configure HAproxy

sudo apt-get update
sudo apt-get install -y haproxy

str_haproxy="frontend http-in\n\tbind *:80\n\tmode http\n\tdefault_backend web-servers\n\nbackend web-servers\n\tmode http\n\tbalance roundrobin\n\tserver 16388-web-01 100.25.12.91:80 check\n\tserver 16388-web-02 52.207.88.254:80 check"
echo -e "$str_haproxy" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
