#!/usr/bin/env bash
# Bash script that install and configure HAproxy

sudo apt-get update
sudo apt-get install -y haproxy

echo "ENABLED=1" >> /etc/default/haproxy

str_haproxy="
frontend httpin
	bind *:80
	default_backend web-servers
backend web-servers
	balance roundrobin
	server 16388-web-01 54.160.91.77:80 check
        server 16388-web-02 52.91.203.69:80 check"

echo -e "$str_haproxy" >> /etc/haproxy/haproxy.cfg

sudo service haproxy reload
