#!/usr/bin/env bash
# init script to start, restart and stop manage_my_process process


start_cmd="./manage_my_process"

if [ "$1" == 'start' ]
then
	eval "$start_cmd" &
	echo manage_my_process started
	echo $(( "$!" + 1 )) > /var/run/my_process.pid
elif [ "$1" == 'stop' ]
then
	pid=$(< /var/run/my_process.pid)
	rm -f /var/run/my_process.pid
	kill -3 $pid
	echo manage_my_process stopped
elif [ "$1" == 'restart' ]
then
	pid=$(< /var/run/my_process.pid)
	kill -3 $pid
	eval "$start_cmd" &
	echo $(( "$!" + 1 )) > /var/run/my_process.pid
	echo manage_my_process restarted
else
	echo "Usage: manage_my_process {start|stop|restart}"
fi
