#!/usr/bin/env bash
# Print numbers from 1 to 100
# print Fizz for multiples of 3
# Buzz for multiples of 5
# and FizzBuzz in place of multiples of 3 and 5

for ((num=1; num <= 100; num++))
do
	if [[ $((num%3)) -eq 0 && $((num%5)) -eq 0 ]]
	then
		echo FizzBuzz
	elif [ $((num%3)) -eq 0 ]
	then
		echo Fizz
	elif [ $((num%5)) -eq 0 ]
	then
		echo Buzz
	else
		echo $num
	fi
done
