#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
# For the fourth iteration display "Bad luck" instead
# For the eigth iteration display "Good luck"

n=0

while [ $n -lt 10 ];
do
	if [ $n -eq 3 ]
	then
		echo bad luck
		((n++))
		continue
	elif [ $n -eq 7 ]
	then
		echo good luck
		((n++))
		continue
	else
		echo Best School
		((n++))
	fi
done
