#!/usr/bin/env bash
# This script displays the time for 12hours and 59hours

passwd_file="/etc/passwd"

# Check if the file exists
if [ -f "$passwd_file" ]
then
    while IFS=":" read -r username _ uid _ _ home_directory _;
    do
        echo "$username:$uid:$home_directory"
    done < "$passwd_file"
fi
